const batedeiras = [
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Mondial',
        cor: 'azul',
        precoCusto: 40,
        precoVenda: 60,
        estoque: 5,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Mondial',
        cor: 'vermelha',
        precoCusto: 40,
        precoVenda: 60,
        estoque: 0,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Mondial',
        cor: 'amarela',
        precoCusto: 40,
        precoVenda: 60,
        estoque: 1,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Mondial',
        cor: 'verde',
        precoCusto: 40,
        precoVenda: 60,
        estoque: 0,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Cadence',
        cor: 'azul',
        precoCusto: 45,
        precoVenda: 85,
        estoque: 0,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Cadence',
        cor: 'amarela',
        precoCusto: 45,
        precoVenda: 85,
        estoque: 2,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Cadence',
        cor: 'vermelha',
        precoCusto: 45,
        precoVenda: 85,
        estoque: 10,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Cadence',
        cor: 'verde',
        precoCusto: 45,
        precoVenda: 85,
        estoque: 2,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Electrolux',
        cor: 'verde',
        precoCusto: 54.90,
        precoVenda: 99.90,
        estoque: 0,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Electrolux',
        cor: 'vermelha',
        precoCusto: 54.90,
        precoVenda: 99.90,
        estoque: 0,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Batedeira',
        marca: 'Electrolux',
        cor: 'azul',
        precoCusto: 54.90,
        precoVenda: 99.90,
        estoque: 5,
    },

]

const smartphones = [
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Smartphone',
        marca: 'Samsung',
        modelo: 'Z Flip',
        cor: 'branco',
        precoCusto: 4000,
        precoVenda: 8000,
        estoque: 2,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Smartphone',
        marca: 'Samsung',
        modelo: 'A10',
        cor: 'azul',
        precoCusto: 1000,
        precoVenda: 1500,
        estoque: 0,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Smartphone',
        marca: 'Samsung',
        modelo: 'A10',
        cor: 'vermelho',
        precoCusto: 1000,
        precoVenda: 1500,
        estoque: 2,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Smartphone',
        marca: 'Xiaomi',
        modelo: 'Note 10',
        cor: 'azul',
        precoCusto: 2000,
        precoVenda: 3000,
        estoque: 5,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Smartphone',
        marca: 'Xiaomi',
        modelo: 'Note 10',
        cor: 'rosa',
        precoCusto: 2000,
        precoVenda: 3000,
        estoque: 0,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Smartphone',
        marca: 'Motorola',
        modelo: 'G 22',
        cor: 'ciano',
        precoCusto: 1870,
        precoVenda: 3500,
        estoque: 1,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Smartphone',
        marca: 'Motorola',
        modelo: 'G 22',
        cor: 'rosa',
        precoCusto: 1870,
        precoVenda: 3500,
        estoque: 2,
    },
]

const televisores = [
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Televisor',
        marca: 'AOC',
        modelo: '32 polegadas',
        precoCusto: 1500,
        precoVenda: 2100,
        estoque: 0,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Televisor',
        marca: 'AOC',
        modelo: '40 polegadas',
        precoCusto: 2000,
        precoVenda: 2500,
        estoque: 2,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Televisor',
        marca: 'AOC',
        modelo: '50 polegadas',
        precoCusto: 3000,
        precoVenda: 4500,
        estoque: 10,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Televisor',
        marca: 'Samsung',
        modelo: '50 polegadas',
        precoCusto: 3400,
        precoVenda: 5200,
        estoque: 2,
    },
    {
        id: Math.random().toString(8).substring(2),
        produto: 'Televisor',
        marca: 'Philco',
        modelo: '32 polegadas',
        precoCusto: 1200,
        precoVenda: 1800,
        estoque: 5,
    },
]

const produtos = [
    ...batedeiras,
    ...smartphones,
    ...televisores
]

export default produtos